Name:           ros-hydro-openni-wrapper
Version:        0.0.2
Release:        0%{?dist}
Summary:        ROS openni_wrapper package

Group:          Development/Libraries
License:        Apache License Version 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       freeglut-devel
Requires:       libusbx-devel
Requires:       ros-hydro-class-loader
Requires:       ros-hydro-cv-bridge
Requires:       ros-hydro-nodelet
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-rospy
Requires:       ros-hydro-std-msgs
BuildRequires:  freeglut-devel
BuildRequires:  java-1.7.0-openjdk
BuildRequires:  java-1.8.0-openjdk
BuildRequires:  libudev-devel
BuildRequires:  libusbx-devel
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-class-loader
BuildRequires:  ros-hydro-cv-bridge
BuildRequires:  ros-hydro-nodelet
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-rospy
BuildRequires:  ros-hydro-std-msgs

%description
The openniWrapper package

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Nov 04 2014 Rares Ambrus <raambrus@kth.se> - 0.0.2-0
- Autogenerated by Bloom

